site_name: J. Adamek personal website
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest
plugins:
  - search
  - mkdocs-jupyter
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Puzzles:
      - Puzzle 1: puzzles/puzzle1.md
      - Puzzle 2: puzzles/puzzle2.md
  - Notebooks:
      - Example: notebooks/example.ipynb
