site_name: Jakub Adamek
site_url: https://KrolKubaV.github.io/personal-site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy         # adds "copy" button to code blocks
  palette:
    - scheme: default          # light mode
      primary: 'indigo'
      accent: 'orange'
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate            # dark mode
      primary: 'indigo'
      accent: 'orange'
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Fira Code'

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences    # advanced code block styling
  - pymdownx.betterem       # improved emphasis handling
  - pymdownx.tilde          # support for strikethrough

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_javascript:
  - https://pyscript.net/latest/pyscript.js

extra_css:
  - https://pyscript.net/latest/pyscript.css


nav:
  - Home: index.md
  - Mathematics of Gambling and Casino Games:
      - Resources: betting/resources.md
      - BlackJack:
          - Start: betting/BlackJack/start.md
  - Puzzles:
      - Project Euler: puzzles/project_euler.md
      - Other: 
          - Puzzle 1: puzzles/other/puzzle1.md
